server:
  port: 4580
  servlet:
    context-path: /api

spring:
  application:
    name: PatientMonitoring

  datasource:
    url: jdbc:mysql://localhost:3306/cs458_project4
    username: cs458
    password: cs458

  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date: yyyy-MM-dd


logging:
  file:
    name: patientmonitoring.log
