server:
  port: 5000
  servlet:
    context-path: /api

spring:
  application:
    name: PatientMonitoring

  datasource:
    url: jdbc:mysql://localhost:3306/cs458_project4
    username: cs458
    password: cs458

  jpa:
    hibernate:
      ddl-auto: create

logging:
  file:
    name: patientmonitoring.log
